from typing import Dict, NamedTuple, Callable, Optional

from BaseClasses import Location


class HereComesNikoLocation(Location):
    game = "Here Comes Niko!"


class HereComesNikoLocationData(NamedTuple):
    region: str
    id: Optional[int] = None
    can_create: Callable = lambda options: True
    locked_item: Optional[str] = None

base_id = 598_145_444_000

location_data_table: Dict[str, HereComesNikoLocationData] = {
    # Coins
    "Give High Frog Lunchbox": HereComesNikoLocationData("Home", base_id + 0),
    #"Letter near crane": HereComesNikoLocationData("Home", base_id + 1),
    #"Get hired": HereComesNikoLocationData("Home", base_id + 2, locked_item="Victory"),
    "Win BIG VOLLEY (HC)": HereComesNikoLocationData("Hairball City", base_id + 3),
    "Dustan on lighthouse": HereComesNikoLocationData("Hairball City", base_id + 4),
    "Gabi's Flowers (HC)": HereComesNikoLocationData("Hairball City", base_id + 5),
    "Gunter on Skyscraper": HereComesNikoLocationData("Hairball City", base_id + 6),
    "Fish with Fischer (HC)": HereComesNikoLocationData("Hairball City", base_id + 7),
    "Give Blessley 30 bugs (HC)": HereComesNikoLocationData("Hairball City", base_id + 8),
    "Unknown CL1_1": HereComesNikoLocationData("Hairball City", base_id + 9),
    "Unknown CL1_2": HereComesNikoLocationData("Hairball City", base_id + 10),
    "Unknown CL1_3": HereComesNikoLocationData("Hairball City", base_id + 11),
    "Unknown CL1_4": HereComesNikoLocationData("Hairball City", base_id + 12),
    "Unknown CL2_1": HereComesNikoLocationData("Hairball City", base_id + 13),
    "Unknown CL2_2": HereComesNikoLocationData("Hairball City", base_id + 14),
    "Unknown CL2_3": HereComesNikoLocationData("Hairball City", base_id + 15),
    "Unknown CL2_4": HereComesNikoLocationData("Hairball City", base_id + 16),
    "Fish with Fischer (TT)": HereComesNikoLocationData("Turbine Town", base_id + 17),
    "Win AIR VOLLEY (TT)": HereComesNikoLocationData("Turbine Town", base_id + 18),
    "Gabi's Flowers (TT)": HereComesNikoLocationData("Turbine Town", base_id + 19),
    "Bring back the wind": HereComesNikoLocationData("Turbine Town", base_id + 20),
    "Give Blessley 30 bugs (TT)": HereComesNikoLocationData("Turbine Town", base_id + 21),
    "Dustan on wind turbine": HereComesNikoLocationData("Turbine Town", base_id + 22),
    "Unknown CL1_1 (TT)": HereComesNikoLocationData("Turbine Town", base_id + 23),
    "Unknown CL1_2 (TT)": HereComesNikoLocationData("Turbine Town", base_id + 24),
    "Unknown CL1_3 (TT)": HereComesNikoLocationData("Turbine Town", base_id + 25),
    "Unknown CL2_1 (TT)": HereComesNikoLocationData("Turbine Town", base_id + 26),
    "Unknown CL2_2 (TT)": HereComesNikoLocationData("Turbine Town", base_id + 27),
    "Get Stijn and Melissa together": HereComesNikoLocationData("Salmon Creek Forest", base_id + 28),
    "Give Mitch 5 Cassettes (SCF)": HereComesNikoLocationData("Salmon Creek Forest", base_id + 29),
    "Dustan on mountain": HereComesNikoLocationData("Salmon Creek Forest", base_id + 30),
    "Collect all 10 seeds (SCF)": HereComesNikoLocationData("Salmon Creek Forest", base_id + 31),
    "Collect 5 Bones (SCF)": HereComesNikoLocationData("Salmon Creek Forest", base_id + 32),
    "Help the tree": HereComesNikoLocationData("Salmon Creek Forest", base_id + 33),
    "Give Blessley 30 bugs (SCF)": HereComesNikoLocationData("Salmon Creek Forest", base_id + 34),
    "Secret waterfall cave": HereComesNikoLocationData("Salmon Creek Forest", base_id + 35),
    "Win SPORTVIVAL (SCF)": HereComesNikoLocationData("Salmon Creek Forest", base_id + 36),
    "Gabi's Flowers (SCF)": HereComesNikoLocationData("Salmon Creek Forest", base_id + 37),
    "Paint 5 graffiti near Nina (SCF)": HereComesNikoLocationData("Salmon Creek Forest", base_id + 38),
    "Give Mai 5 Cassettes (SCF)": HereComesNikoLocationData("Salmon Creek Forest", base_id + 39),
    "Fish with Fischer (SCF)": HereComesNikoLocationData("Salmon Creek Forest", base_id + 40),
    "Unknown CL2_1 (SCF)": HereComesNikoLocationData("Salmon Creek Forest", base_id + 41),
    "Unknown CL2_2 (SCF)": HereComesNikoLocationData("Salmon Creek Forest", base_id + 42),
    "Unknown CL2_3 (SCF)": HereComesNikoLocationData("Salmon Creek Forest", base_id + 43),
    "End of 2D section": HereComesNikoLocationData("Public Pool", base_id + 44),
    "Give Mai 5 Cassettes (PP)": HereComesNikoLocationData("Public Pool", base_id + 45),
    "Help Blippy (PP)": HereComesNikoLocationData("Public Pool", base_id + 46),
    "Help Blippy 2 (PP)": HereComesNikoLocationData("Public Pool", base_id + 47),
    "Fish with Fischer (PP)": HereComesNikoLocationData("Public Pool", base_id + 48),
    "Solve the crime": HereComesNikoLocationData("Public Pool", base_id + 49),
    "Unknown CL2_1 (PP)": HereComesNikoLocationData("Public Pool", base_id + 50),
    "Unknown CL2_2 (PP)": HereComesNikoLocationData("Public Pool", base_id + 51),
    "Unknown CL2_3 (PP)": HereComesNikoLocationData("Public Pool", base_id + 52),
    "Unknown CL2_4 (PP)": HereComesNikoLocationData("Public Pool", base_id + 53),
    "Bring Louist to Serschel (Bath)": HereComesNikoLocationData("Bathhouse", base_id + 54),
    "Collect all 10 seeds (Bath)": HereComesNikoLocationData("Bathhouse", base_id + 55),
    "Help Paul": HereComesNikoLocationData("Bathhouse", base_id + 56),
    "Paint 5 graffiti near Nina (Bath)": HereComesNikoLocationData("Bathhouse", base_id + 57),
    "Give Mitch 5 Cassettes (Bath)": HereComesNikoLocationData("Bathhouse", base_id + 58),
    "Give Mai 5 Cassettes (Bath)": HereComesNikoLocationData("Bathhouse", base_id + 59),
    "Dustan on Bathhouse": HereComesNikoLocationData("Bathhouse", base_id + 60),
    "Win LONG VOLLEY (Bath)": HereComesNikoLocationData("Bathhouse", base_id + 61),
    "Beat Game Kid": HereComesNikoLocationData("Bathhouse", base_id + 62),
    "Unknown CL2_1 (Bath)": HereComesNikoLocationData("Bathhouse", base_id + 63),
    "Unknown CL2_2 (Bath)": HereComesNikoLocationData("Bathhouse", base_id + 64),
    "Unknown CL2_3 (Bath)": HereComesNikoLocationData("Bathhouse", base_id + 65),
    "Unknown CL2_4 (Bath)": HereComesNikoLocationData("Bathhouse", base_id + 66),
    "Unknown CL2_5 (Bath)": HereComesNikoLocationData("Bathhouse", base_id + 67),
    "Give Mai 5 Cassettes (HQ)": HereComesNikoLocationData("Tadpole HQ", base_id + 68),
    "Give Mitch 5 Cassettes (HQ)": HereComesNikoLocationData("Tadpole HQ", base_id + 69),
    "Listen to King Frog": HereComesNikoLocationData("Tadpole HQ", base_id + 70),
    "Win HUGE VOLLEY (HQ)": HereComesNikoLocationData("Tadpole HQ", base_id + 71),
    "Fish with Fischer (HQ)": HereComesNikoLocationData("Tadpole HQ", base_id + 72),
    "Gabi's Flowers (HQ)": HereComesNikoLocationData("Tadpole HQ", base_id + 73),
    "Help Blippy Coin (HQ)": HereComesNikoLocationData("Tadpole HQ", base_id + 74),
    "Give Blessley 30 bugs (HQ)": HereComesNikoLocationData("Tadpole HQ", base_id + 75),
    "Bring Louist to Serschel (HQ)": HereComesNikoLocationData("Tadpole HQ", base_id + 76),
    "Help Blippy Bone (HQ)": HereComesNikoLocationData("Tadpole HQ", base_id + 77),
    #"": HereComesNikoLocationData("Home", base_id + 78),
    #"": HereComesNikoLocationData("Home", base_id + 79),
    #"": HereComesNikoLocationData("Home", base_id + 80),

    # Letters
    "Letter near crane": HereComesNikoLocationData("Home", base_id + 80),
    "Letter on a tree": HereComesNikoLocationData("Hairball City", base_id + 81),
    "Letter behind train": HereComesNikoLocationData("Hairball City", base_id + 82),
    "Letter behind wind dragon": HereComesNikoLocationData("Turbine Town", base_id + 83),
    "Letter in sunken container": HereComesNikoLocationData("Turbine Town", base_id + 84),
    "Letter in locked cave": HereComesNikoLocationData("Salmon Creek Forest", base_id + 85),
    "Letter behind waterfall": HereComesNikoLocationData("Salmon Creek Forest", base_id + 86),
    "Letter start of 2D section": HereComesNikoLocationData("Public Pool", base_id + 87),
    "Letter end of 2D section": HereComesNikoLocationData("Public Pool", base_id + 88),
    "Letter behind axolotl family": HereComesNikoLocationData("Bathhouse", base_id + 89),
    "Letter near Game Kid": HereComesNikoLocationData("Bathhouse", base_id + 90),

    # Keys
    "Key inside container": HereComesNikoLocationData("Turbine Town", base_id + 91),
    "Key on tall island": HereComesNikoLocationData("Turbine Town", base_id + 92),
    "Key on rock in ocean": HereComesNikoLocationData("Salmon Creek Forest", base_id + 93),
    "Key in pond": HereComesNikoLocationData("Salmon Creek Forest", base_id + 94),
    "Key near SPORTVIVAL": HereComesNikoLocationData("Salmon Creek Forest", base_id + 95),
    "Key over breakable box": HereComesNikoLocationData("Public Pool", base_id + 96),
    "Key on torii": HereComesNikoLocationData("Bathhouse", base_id + 97),
    "Key near bathhouse box": HereComesNikoLocationData("Bathhouse", base_id + 98),
    "Key under Moomy": HereComesNikoLocationData("Bathhouse", base_id + 99),

    # Cassettes
    "Cassette Behind Pepper": HereComesNikoLocationData("Hairball City", base_id+100),
    "On frog statue (HC)": HereComesNikoLocationData("Hairball City", base_id + 101),
    "Big umbrella": HereComesNikoLocationData("Hairball City", base_id + 102),
    "Lighthouse": HereComesNikoLocationData("Hairball City", base_id + 103),
    "On palm tree (HC)": HereComesNikoLocationData("Hairball City", base_id + 104),
    "Inside the tunnel": HereComesNikoLocationData("Hairball City", base_id + 105),
    "Breakable box on small island": HereComesNikoLocationData("Hairball City", base_id + 106),
    "Behind lighthouse": HereComesNikoLocationData("Hairball City", base_id + 107),
    "Near bench on small island": HereComesNikoLocationData("Hairball City", base_id + 108),
    "Behind frog statue (HC)": HereComesNikoLocationData("Hairball City", base_id + 109),
    #"": HereComesNikoLocationData("Hairball City", base_id + 110),
    "Inside container on water": HereComesNikoLocationData("Turbine Town", base_id + 111),
    "Rocks on water": HereComesNikoLocationData("Turbine Town", base_id + 112),
    "On top of containers": HereComesNikoLocationData("Turbine Town", base_id + 113),
    "Behind Blessley (TT)": HereComesNikoLocationData("Turbine Town", base_id + 114),
    "Container with A LOT of buttons": HereComesNikoLocationData("Turbine Town", base_id + 115),
    "Inside container behind Pepper": HereComesNikoLocationData("Turbine Town", base_id + 116),
    "Next to turbine": HereComesNikoLocationData("Turbine Town", base_id + 117),
    "Next to torii gates": HereComesNikoLocationData("Turbine Town", base_id + 118),
    "Near fishing containers": HereComesNikoLocationData("Turbine Town", base_id + 119),
    "Floating above water (TT)": HereComesNikoLocationData("Turbine Town", base_id + 120),
    #"": HereComesNikoLocationData("Turbine Town", base_id + 121),
    "Behind train": HereComesNikoLocationData("Salmon Creek Forest", base_id + 122),
    "Wooden bridge": HereComesNikoLocationData("Salmon Creek Forest", base_id + 123),
    "On treehouse": HereComesNikoLocationData("Salmon Creek Forest", base_id + 124),
    "Rocks near mountain (SCF)": HereComesNikoLocationData("Salmon Creek Forest", base_id + 125),
    "Near void in waterfall cave": HereComesNikoLocationData("Salmon Creek Forest", base_id + 126),
    "Inside boxes behind waterfall cave": HereComesNikoLocationData("Salmon Creek Forest", base_id + 127),
    "Next to treehouse": HereComesNikoLocationData("Salmon Creek Forest", base_id + 128),
    "Rocks in ocean (SCF)": HereComesNikoLocationData("Salmon Creek Forest", base_id + 129),
    "Behind mountain (SCF)": HereComesNikoLocationData("Salmon Creek Forest", base_id + 130),
    "Next to Treeman": HereComesNikoLocationData("Salmon Creek Forest", base_id + 131),
    "Near hamster ball": HereComesNikoLocationData("Salmon Creek Forest", base_id + 132),
    #"": HereComesNikoLocationData("Salmon Creek Forest", base_id + 133),
    "Frog statue (PP)": HereComesNikoLocationData("Public Pool", base_id + 134),
    "On springboard": HereComesNikoLocationData("Public Pool", base_id + 135),
    "Small island on the left": HereComesNikoLocationData("Public Pool", base_id + 136),
    "Rocks in ocean (PP)": HereComesNikoLocationData("Public Pool", base_id + 137),
    "Inside the pool": HereComesNikoLocationData("Public Pool", base_id + 138),
    "Inside the BIG pool": HereComesNikoLocationData("Public Pool", base_id + 139),
    "Behind frog statue (PP)": HereComesNikoLocationData("Public Pool", base_id + 140),
    "Palm tree (PP)": HereComesNikoLocationData("Public Pool", base_id + 141),
    "Breakable box in pool": HereComesNikoLocationData("Public Pool", base_id + 142),
    "Above BIG pool": HereComesNikoLocationData("Public Pool", base_id + 143),
    #"": HereComesNikoLocationData("Public Pool", base_id + 144),
    "Frog statue butt (Bath)": HereComesNikoLocationData("Bathhouse", base_id + 145),
    "Near axolotl family in water": HereComesNikoLocationData("Bathhouse", base_id + 146),
    "Hut in water": HereComesNikoLocationData("Bathhouse", base_id + 147),
    "Giant frog statue (Bath)": HereComesNikoLocationData("Bathhouse", base_id + 148),
    "Lamp near Moomy": HereComesNikoLocationData("Bathhouse", base_id + 149),
    "Behind LONG VOLLEY": HereComesNikoLocationData("Bathhouse", base_id + 150),
    "Behind waterfall (Bath)": HereComesNikoLocationData("Bathhouse", base_id + 151),
    "Fan to fan": HereComesNikoLocationData("Bathhouse", base_id + 152),
    "On pipes": HereComesNikoLocationData("Bathhouse", base_id + 153),
    "Mahjong hideout": HereComesNikoLocationData("Bathhouse", base_id + 154),
    #"": HereComesNikoLocationData("Bathhouse", base_id + 155),
    "Between skyscrapers": HereComesNikoLocationData("Tadpole HQ", base_id + 156),
    "Next to skyscrapers": HereComesNikoLocationData("Tadpole HQ", base_id + 157),
    "?": HereComesNikoLocationData("Tadpole HQ", base_id + 158),
    "Main skyscraper backside": HereComesNikoLocationData("Tadpole HQ", base_id + 159),
    "??": HereComesNikoLocationData("Tadpole HQ", base_id + 160),
    "King frog statue": HereComesNikoLocationData("Tadpole HQ", base_id + 161),
    "Breakable box near Blessley": HereComesNikoLocationData("Tadpole HQ", base_id + 162),
    "Rocks in ocean (HQ)": HereComesNikoLocationData("Tadpole HQ", base_id + 163),
    "Under giant umbrella": HereComesNikoLocationData("Tadpole HQ", base_id + 164),
    "Inbetween buildings": HereComesNikoLocationData("Tadpole HQ", base_id + 165),

    # "": HereComesNikoLocationData("Gary's Garden", base_id + 163),
    # "": HereComesNikoLocationData("Gary's Garden", base_id + 163),
    # "": HereComesNikoLocationData("Gary's Garden", base_id + 163),
    # "": HereComesNikoLocationData("Gary's Garden", base_id + 163),
    # "": HereComesNikoLocationData("Gary's Garden", base_id + 163),
    # "": HereComesNikoLocationData("Gary's Garden", base_id + 163),
    # "": HereComesNikoLocationData("Gary's Garden", base_id + 163),
    # "": HereComesNikoLocationData("Gary's Garden", base_id + 163),
    # "": HereComesNikoLocationData("Gary's Garden", base_id + 163),

    # Misc
    "Give 250 Apples to Dojo guy": HereComesNikoLocationData("Tadpole HQ", base_id + 166),
    "Contact List 1": HereComesNikoLocationData("Salmon Creek Forest", base_id + 167),
    "Contact List 2": HereComesNikoLocationData("Tadpole HQ", base_id + 168),

    # Victory
    #"You're hired!": HereComesNikoLocationData(region="Home Party", locked_item="Victory"),
}

location_table = {name: data.id for name, data in location_data_table.items() if data.id is not None}
id_to_location_table = {data.id: name for name, data in location_data_table.items() if data.id is not None}
locked_locations = {name: data for name, data in location_data_table.items() if data.locked_item}



